
Files already downloaded and verified
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Training:   0% 0/50000 [00:15<?, ?it/s, loss=1.3863]





Evaluating:  90% 350/391 [00:08<00:01, 39.71it/s]




























































































get_inception_feature: 100% 49850/50000 [03:03<00:00, 263.88it/s]
















































































































































































































































































































































































Training:   4% 1999/50000 [17:23<4:51:51,  2.74it/s, loss=1.0164]





Evaluating:  93% 365/391 [00:09<00:00, 39.75it/s]
































































































get_inception_feature:  99% 49700/50000 [03:11<00:01, 258.11it/s]





















































































































































































































































































































































































Training:   8% 3999/50000 [34:41<4:40:08,  2.74it/s, loss=0.8323]






































































































get_inception_feature: 100% 49800/50000 [03:12<00:00, 256.84it/s]



















































































































































































































































































































































































Training:  12% 5999/50000 [51:59<4:27:26,  2.74it/s, loss=0.7253]





Evaluating:  83% 326/391 [00:08<00:01, 39.84it/s]

































































































Training:  12% 6000/50000 [55:38<807:09:10, 66.04s/it, loss=0.6664]



















































































































































































































































































































































































Training:  16% 7999/50000 [1:09:16<4:17:35,  2.72it/s, loss=0.6536]




Evaluating:  81% 315/391 [00:07<00:01, 39.57it/s]

































































































get_inception_feature: 100% 49900/50000 [03:13<00:00, 257.18it/s]



























































































































































































































































Training:  19% 9360/50000 [1:22:08<5:56:37,  1.90it/s, loss=0.5027]
Traceback (most recent call last):
  File "starter.py", line 25, in <module>
    main(config)
  File "starter.py", line 10, in main
    launcher(config)
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/launch.py", line 259, in launcher
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/launch.py", line 170, in train
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/source/utils.py", line 25, in infiniteloop
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 165, in get_preparation_data
    dir=os.getcwd(),
FileNotFoundError: [Errno 2] No such file or directory