
Files already downloaded and verified
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Training:   0% 0/50000 [00:16<?, ?it/s, loss=1.3863]
Traceback (most recent call last):
  File "starter.py", line 24, in <module>
    main(config)
  File "starter.py", line 10, in main
    launcher(config)
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/launch.py", line 238, in launcher
    train(config)
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/launch.py", line 201, in train
    config.log.logdir, 'sample', '%d.png' % step))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/utils.py", line 136, in save_image
    im.save(fp, format=format)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2131, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './logs/sample/1.png'